version: "3.8"

services:
  backend:
   build: ./backend
   container_name: back_p6
   environment:
    - DB_USER=/run/secrets/db_user
    - DB_PASS=/run/secrets/db_pass
    - DB_NAME=/run/secrets/db_name
    - PORT=3000
   secrets:
     - db_user
     - db_pass
     - db_name
   volumes:
     - ./backend:/app
    # Pour éviter un bug avec bcrypt
     - /app/node_modules
   ports:
    - 3000:3000
   networks:
     - front-network
     - back-network
   restart: unless-stopped

  frontend:
   build: ./frontend
   container_name: front_p6
   ports:
     - 8080:8080
   networks:
     - front-network

  database:
   image: mongo:5.0
   container_name: db_p6
   environment:
    - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_admin_user
    - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_admin_pass
    - MONGO_INITDB_USERNAME_FILE=/run/secrets/db_user
    - MONGO_INITDB_PASSWORD_FILE=/run/secrets/db_pass
    - MONGO_INITDB_DATABASE_FILE=/run/secrets/db_name 
   volumes:
     - db_data:/data/db
     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro 
   secrets:
     - db_admin_user
     - db_admin_pass
     - db_user
     - db_pass
     - db_name 
   restart: unless-stopped
   ports:
    - 27017:27017
   networks:
    - back-network

networks:
  back-network:
  front-network:

volumes:
 db_data:

secrets:
 db_admin_user:
  file: ./secrets/db_admin_user
 db_admin_pass:
  file: ./secrets/db_admin_pass
 db_pass:
  file: ./secrets/db_pass
 db_user:
  file: ./secrets/db_user
 db_name:
  file: ./secrets/db_name
  