version: "3.8"

services:
  backend:
   build: ./backend
   container_name: back_p6
   environment:
    - MONGODB_CONNSTRING=mongodb://database:27017
   volumes:
     - ./backend:/app
    # Pour éviter un bug avec bcrypt
     - /app/node_modules
   ports:
    - 3000:3000
   networks:
     - front-network
     - back-network
   restart: always

  frontend:
   build: ./frontend
   container_name: front_p6
   ports:
     - 8080:8080
   networks:
     - front-network

  database:
   image: mongo:5.0
   container_name: db_p6
   restart: always
   ports:
    - 27017:27017
   networks:
    - back-network

networks:
  back-network:
  front-network: